### PR TITLE
Feature:

### PR DESCRIPTION
**Pull request by dunnodepends**
Add AutofacDiagnosticExtensions.cs

Miscellanea:
SDK Knocked-up 7.0.7 from 6.0.401.

Updated Nuged; added:
   Autofac.Extensions.DependencyInjection
   Microsoft.AspNetCore.Http.Abstractions
   Microsoft.NETCore.DotNetAppHost

Dropped Framework; added .NET7

### CODE REVIEW

**Comment by tillig** [comment]
This ideally supports the same frameworks as core Autofac, so removing some of the lower frameworks is not ideal.

It looks like there are a lot of suppressions from the analyzers - we actually do need the analyzers to pass without suppressions, which means things like documentation and proper member ordering/naming are required.

This should work without any ASP.NET references since Autofac is not specific to an app type.

We don't support code that has different behavior in debug mode. We don't release debug builds and don't test those paths. All debug-only code should be removed.

I'm not entirely sure what this feature is for. The description in the PR just says that since extensions were added but it's not clear - from the title or description - what this _is_. 

Anyway, thanks for the contribution, but it looks like there's quite a bit to update here before we might be able to take this.

**Comment by dunnodepends** [comment]
Thank you!  I will work-on the configurability.  Essentially, this integrates into the application configuration-step using `app.UseAutoFacDOTDiagnostics()`.

Yes, I will look into those concerns. Thank you for the guidance!  Yes, I can remove the debug-conditional parts as I see this is launched from within an `app.Environment.IsDevelopment()`-block.

```csharp
if (app.Environment.IsDevelopment())
{
  app.UseDeveloperExceptionPage();
  app.UseShowAllServicesMiddleware();
#if DEBUG
  app.UseAutoFacDOTDiagnostics(); //daab+ 20230810: autofac analysis
#endif
}
else
{
  app.UseExceptionHandler("/Home/Error");
  app.UseHsts();
}
app.UseRouting();
```

**Comment by dunnodepends** [comment]
The addition is that it generates the diagrams contemporaneously along with the DOT code without manual intervention to convert the latter.

**Comment by tillig** [comment]
Given there's been no action on this in about nine months, I'm going to close this PR. If this is still desired, open a new PR with the fixes noted earlier.

**Pull request closed without merging**
